name: "🐛 Bug Report"
description: "Report a bug with a Sunbunny plugin"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill in the details below.

  - type: dropdown
    id: plugin
    attributes:
      label: "Plugin"
      description: "Which Sunbunny plugin is this about?"
      options:
        - Panoramatone
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: "Plugin version"
      description: "Which version of the plugin are you using?"
      placeholder: "e.g. 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      options:
        - Windows 10
        - Windows 11
        - macOS 13 Ventura
        - macOS 14 Sonoma
        - macOS 15 Sequoia
        - Ubuntu 22.04
        - Ubuntu 24.04
        - Fedora 39+
        - Arch Linux
        - Other (please specify below)
    validations:
      required: true

  - type: input
    id: daw
    attributes:
      label: "DAW (host)"
      description: "Which DAW and version are you using?"
      placeholder: "e.g. Ableton Live 12, Reaper 7.10, Bitwig 5.1"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "What did you do?"
      placeholder: |
        1. Load the plugin on a track
        2. Set Rate to 5 Hz
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      description: "What actually happened?"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs / screenshots"
      description: "Paste any relevant logs or attach screenshots."
      placeholder: "Drag & drop screenshots here or paste log output."
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: "Additional context"
      description: "Anything else? (buffer size, sample rate, CPU, etc.)"
    validations:
      required: false
