name: "✨ Feature Request"
description: "Suggest a new feature or improvement"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? We'd love to hear it. Fill in what you can below.

  - type: textarea
    id: problem
    attributes:
      label: "Problem / motivation"
      description: "What problem does this solve? What's the use case?"
      placeholder: "I often find myself wanting to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed solution"
      description: "How would you like this to work?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives considered"
      description: "Any workarounds or alternatives you've tried?"
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: "Additional context"
      description: "Anything else? Screenshots, examples, references?"
    validations:
      required: false
